#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

# Commands to execute in the container
command() {
  cat - <<EOF
git config --global --add safe.directory /docs
git config --global user.name "$(git config --get user.name)"
git config --global user.email "$(git config --get user.email)"
mike $@
EOF
}

# run mike
command "$@" | docker run --name mike --rm -i \
  -v ${PWD}:/docs \
  -v ${HOME}/.ssh:/root/.ssh \
  -v ${SSH_AUTH_SOCK}:/ssh-agent \
  -e SSH_AUTH_SOCK=/ssh-agent \
  --entrypoint="sh" \
  eoepca/mkdocs-material \
  -

# clean-up
sudo rm -rf site
sudo chown -R $(id -u):$(id -g) .git
