site_name: EOEPCA System Description
site_url: https://system-description.docs.eoepca.org
repo_url: https://github.com/EOEPCA/system-description
edit_uri: ""

# Site navigation
nav:
  - System Description:
    - index.md
    - System:
      - system/overview.md
    - Processing:
      - processing/ades.md
      - processing/application-hub.md
      - processing/AP-validator.md
    - Resources:
      - resources/catalogue.md
      - resources/data-access.md
      - resources/registration-api.md
      - resources/workspace.md
    - User Management:
      - iam/iam-overview.md
      - iam/login-service.md
      - iam/pdp.md
      - Policy Enforcement:
        - iam/resource-guard.md
        - iam/pep.md
        - iam/uma-user-agent.md
      - iam/user-profile.md

theme:
  # name: mkdocs
  # name: readthedocs
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/
  # locale: en
  # custom_dir: my_theme_customizations/
  custom_dir: overrides
  # static_templates:
  #   - sitemap.html
  # include_sidebar: false

  # highlightjs: true
  # hljs_languages:
  #   - yaml
  navigation_depth: 4

  # For `material` theme...
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - toc.integrate
    - navigation.top
    - content.code.copy

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tilde
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4

extra:
  version:
    provider: mike

# docs_dir: docs
# site_dir: site
# extra_css:
#     - css/extra.css
#     - css/second_extra.css
# extra_javascript: []
# extra_templates: []
# extra: {}
# use_directory_urls: true
# strict: false
# dev_addr: 127.0.0.1:8000
# plugins:
#   - search:
#     separator: '[\s\-\.]+'
#     min_search_length: 3
#     lang: en
#     prebuild_index: False
#     indexing: full
#   - your_other_plugin
